name: "Continuous Integration"

on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

env:
  COMPOSER_FLAGS: "--ansi --no-interaction --no-progress --no-suggest --prefer-dist"
  COVERAGE_FLAGS: "--coverage-text --coverage-clover build/logs/clover.xml"

jobs:
  tests:
    name: PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php-version:
          - "5.3"
          - "5.4"
          - "5.5"
          - "5.6"
          - "7.0"
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
        include:
          - php-version: 5.3
            dependencies: lowest
          - php-version: 5.6
            coverage: true
          - php-version: 7.4
            coverage: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, dom
          coverage: xdebug
      - name: Setup Problem Matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ matrix.php-version }}-composer-
      - name: Install Composer dependencies (highest)
        if: "matrix.dependencies != 'lowest'"
        run: composer update ${{ env.COMPOSER_FLAGS }}
      - name: Install Composer dependencies (lowest)
        if: "matrix.dependencies == 'lowest'"
        run: composer update ${{ env.COMPOSER_FLAGS }} --prefer-lowest --prefer-stable
      - name: Test with phpunit (with coverage)
        if: "matrix.coverage == 'true'"
        run: vendor/bin/phpunit ${{ env.COVERAGE_FLAGS }}
      - name: Test with phpunit (without coverage)
        if: "matrix.coverage != 'true'"
        run: vendor/bin/phpunit
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: run-${{ matrix.php-version }}
          parallel: true

  finish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true

